# Generated by Django 5.0 on 2023-12-19 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_messagerecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageRecord',
        ),
    ]
